name: Update Latest Branch

on:
  release:
    types: [published]

jobs:
  clone_main_to_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create latest branch
        run: git checkout -b latest

      - name: Push latest branch
        run: |
          git push origin latest
